module.exports = {
  devServer: {
    proxy: {

      '/api': {

          target: "http://localhost",

          changeOrigin: true,

          secure: false,

          pathRewrite: {

              "^/api": ""

          }

      },
    port: 8080,
    open: true
  },
  baseUrl: '',
  lintOnSave: false,
  publicPath: "/palenciacine/",
  outputDir: "dist",
  assetsDir: "static",//Set the directory where the static resources (js, css, img, fonts) generated by the package will be placed.
  indexPath: 'index.html'//Used to set the storage location of the index.html file generated by the package
}

}